# This file was generated by GoReleaser. DO NOT EDIT.
cask "casemd" do
  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "efbe8a79eed6f4b083650b3e0c0b58ea778f122ff99c27bc1da6d72705aca983"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6e27c1ce028a18e9d5afce5a539ae9febd9d4734f0e2026bc4cc7124228f474"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac4dffa7a6b6af8c3ddf77534291a152d15b5ecd65276250edbaba42fd4e3439"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48ae9379d3ab5b85ce83ce7d466141fa1d76bfdd878bd63bf4a48b0353277f29"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "casemd"
  desc "Convert structured Markdown inspection checklists into CSV files and spreadsheets."
  homepage "https://github.com/9renpoto/casemd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "casemd"

  # No zap stanza required
end
