# This file was generated by GoReleaser. DO NOT EDIT.
cask "casemd" do
  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "3a79c8cf1aa2a094e793dcac0d98ad0a0bffee1a3e2cbd1d24ea4d959bcd0df7"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d8e1a99dc9fbc99c79dcf364ad01726c9f764fdc8e14bb2108383ddbf51dac5"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e0d74faabb717eafc914227eb4523c53eb3b865a3e61429b4a4a10e5b433491d"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eccffa92d96644589a6201648f3a907e29ce208c09c713c2f42a399623f755b7"
      url "https://github.com/9renpoto/casemd/releases/download/v#{version}/casemd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "casemd"
  desc "Convert structured Markdown inspection checklists into CSV files and spreadsheets."
  homepage "https://github.com/9renpoto/casemd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "casemd"

  # No zap stanza required
end
